export const surpriseMePrompts = [
  "un fauteuil en forme d'avocat",
  "une peinture à l'huile surréaliste et onirique de Salvador Dalí représentant un chat jouant aux dames",
  "des ours en peluche faisant leurs courses au Japon, ukiyo-e",
  "une peinture à l'huile de Matisse représentant un robot humanoïde jouant aux échecs",
  "un panda savant fou mélangeant des produits chimiques pétillants, art numérique",
  "une photographie macro de deux souris à Hawaï, chacune portant un petit maillot de bain et tenant une petite planche de surf, art numérique",
  "rendu 3D d'un joli poisson tropical dans un aquarium sur un fond bleu foncé, art numérique",
  "un astronaute se prélassant dans une station balnéaire tropicale dans l'espace, vaporwave",
  "un portrait à l'huile d'un capybara portant des robes royales médiévales et une couronne ornée sur un fond sombre",
  "un vitrail représentant un hamburger et des frites",
  "un dessin au crayon et à l'aquarelle d'une ville lumineuse du futur avec des voitures volantes",
  "un espace lounge éclairé par le soleil avec une piscine à l'eau claire et une autre à l'eau rose pastel translucide, à côté d'une grande fenêtre, art numérique",
  "un shiba inu qui lit l'avenir dans un énorme hamburger, art numérique",
  "une loutre de mer avec une boucle d'oreille de perle par Johannes Vermeer",
  "un dessin à la craie à l'huile d'un chat contrarié dans un vaisseau spatial",
  "une peinture d'un renard dans le style de la Nuit étoilée",
  "un bol de soupe qui ressemble à un monstre, tricoté en laine",
  "un jouet en peluche robot assis contre un mur jaune",
  "un coucher de soleil dans le style synthwave au-dessus de l'eau réfléchissante de la mer, art numérique",
  "deux tours futuristes avec une passerelle couverte de végétation luxuriante, art numérique",
  "rendu 3D d'une montgolfière aux couleurs de l'arc-en-ciel volant au-dessus d'un lac réfléchissant",
  "une couverture de bande dessinée d'un super-héros portant des écouteurs",
  "une explosion centrée de poudre colorée sur un fond noir",
  "une photo d'un chien samoyède avec la langue qui dépasse en train d'étreindre un chat siamois blanc",
  "une photo d'un monstre en fourrure blanche debout dans une pièce violette",
  "une photo de la sculpture de David de Michel-Ange portant des écouteurs et jouant de la musique",
  "un samouraï chevauchant un cheval sur Mars, lomographie",
  "une Cadillac moderne et élégante roulant sur l'autoroute Gardiner avec le centre-ville de Toronto en arrière-plan, avec un effet de flare, photographie 50mm",
  "une photographie réaliste d'une jeune femme aux yeux bleus et aux cheveux blonds",
  "un homme debout devant une porte des étoiles vers une autre dimension",
  "Bob l'éponge dans le Projet Blair Witch",
  "un vélociraptor travaillant à un stand de hot-dogs, lomographie",
  "un homme marchant dans les rues animées de Kowloon la nuit, éclairées par de nombreux panneaux lumineux au néon, objectif 50mm",
  "un barbecue qui est vivant, dans le style d'un film d'animation Pixar",
  "une boîte de nuit futuriste de cyborgs, lumières au néon",
  "la version japonaise perdue depuis longtemps de Star Wars en anime de 1990",
  "un hamburger en forme de cube Rubik, photographie alimentaire professionnelle",
  "un hérisson dans le style synthwave, Blade Runner Cyberpunk",
  "un astronaute rencontrant une forme de vie extraterrestre sur une planète lointaine, photographie",
  "un dinosaure explorant Cape Town, photographie",
  "un homme tombant amoureux de son ordinateur, art numérique",
  "une photographie d'un cyborg explorant Tokyo la nuit, lomographie",
  "Dracula se promenant dans les rues de New York dans les années 1920, photographie en noir et blanc",
  "avion synthwave",
  "un homme se promène dans les rues pluvieuses de Tokyo, avec des enseignes lumineuses au néon, objectif 50mm",
  "une navette spatiale volant au-dessus de Cape Town, art numérique",
];
